RezaJodeiri/CXR-Capstone

- .github/pull_request_template.md
- docs/DevelopmentPlan/DevelopmentPlan.tex
- Section for Workflow plan
https://github.com/RezaJodeiri/CXR-Capstone/issues/2
> Dev plan nathan

- docs/SRS/SRS.tex
> Change Section 4 to match rubric

- docs/HazardAnalysis/HazardAnalysis.tex
> Reflection part 4

- docs/VnVPlan/VnVPlan.tex
Changes for Part 5
[link](https://github.com/RezaJodeiri/CXR-Capstone/issues/51)
> Some changes for Part 5

- docs/VnVPlan/VnVPlan.tex
Added all of 2, and section 3.1, 3.2
> VNV Sections 2 and Section 3.1, 3.2 

- docs/VnVPlan/VnVPlan.tex
> Section 3.4, 3.5, 3.6, 3.7

- docs/VnVPlan/VnVPlan.tex
Added more information under 3.2
> VNV - Added a checklist for SRS

- README.md
- src/ai-services/torchxrayvision/requirements.txt
- src/ai-services/torchxrayvision/torch_app.py
- src/backend/api/predict.py
- src/backend/runtime/data/prediction_services.py
- src/frontend/src/pages/PredictionPage.jsx
- src/frontend/src/services/api.js
> feat: Add DCM image support

- docs/Design/SoftArchitecture/MG.tex
- docs/Design/SoftDetailedDes/MIS.tex
> MIS: section 3, 4; MG: 3.1,2,3

- docs/Design/SoftArchitecture/MG.tex
> Section 4 Likely and unlikely Changes

- docs/Design/SoftArchitecture/MG.tex
Add behaviour hiding module for section 7 (M5-10)
> Section 7 M5-10

- src/backend/runtime/__init__.py
- src/backend/runtime/data/aws_s3.py
Using pre-assigned url to upload/download files to/from s3
> Using pre-assigned url to upload/download files to/from s3

- src/backend/api/file-handler.py
- src/backend/api/fileHandler.py
- src/backend/app.py
- src/backend/runtime/__init__.py
add endpoints for s3 upload/download
> add endpoints for s3 upload/download

- src/frontend/src/components/Patient/CreateMedicalRecord.jsx
S3 backend integration with frontend
> S3 backend integration with frontend

- src/ai-services/torchxrayvision/requirements.txt
- src/backend/api/doctor.py
- src/backend/api/oauth.py
- src/backend/app.py
- src/backend/decorators/login_required.py
- src/backend/runtime/data/aws_cognito.py
- src/frontend/package.json
- src/frontend/src/App.jsx
- src/frontend/src/components/Buttons.jsx
- src/frontend/src/components/Patient/PatientInfo.jsx
- src/frontend/src/components/Patient/PatientMedicalRecords.jsx
- src/frontend/src/components/Patient/PatientOverview.jsx
- src/frontend/src/components/Sidebar.jsx
- src/frontend/src/components/TopBar.jsx
- src/frontend/src/pages/PatientDetailsPage.jsx
- src/frontend/src/pages/PatientsPage.jsx
- src/frontend/src/pages/SettingPage.jsx
- src/frontend/src/router.json
- src/frontend/src/services/api.js
- test/backend/api/test_oauth.py
> patients + Doctor creation

- src/frontend/src/components/Patient/CreateMedicalRecord.jsx
- src/frontend/src/components/Patient/PatientMedicalRecords.jsx
>  Bugfix(frontend): Create record props not resetting

- src/backend/runtime/__init__.py
- src/backend/runtime/data/aws_s3.py
- src/frontend/src/components/Patient/CreateMedicalRecord.jsx
- src/frontend/src/services/api.js
> S3 integration 

- docs/VnVReport/VnVReport.tex
- src/backend/runtime/data/mocktest.py
- src/backend/test/test_aws_conito.py
> [Documentation] VNV Report for FRs

- package-lock.json
- package.json
- src/frontend/babel.config.js
- src/frontend/jest.config.js
- src/frontend/package.json
- src/frontend/src/components/Patient/CreateMedicalRecord.jsx
- src/frontend/src/services/api.js
- test/frontend/src/services/__tests__/api.test.js
> Jest unit tests

- .github/workflows/cicd.yml
> Test frontend

- src/ai-services/torchxrayvision/Dockerfile
- src/backend/Dockerfile
- src/infrastructure/.gitignore
- src/infrastructure/README
- src/infrastructure/main.tf
- src/infrastructure/state.tf
> Ground work for infrastructure

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- src/ai-services/torchxrayvision/torch_app.py
- src/infrastructure/main.tf
> Production

- src/docker-compose.yml
- src/frontend/Dockerfile
- src/frontend/local.Dockerfile
- src/frontend/nginx.conf
- src/frontend/src/App.jsx
- src/frontend/src/components/TopBar.jsx
- src/frontend/src/context/Authentication.js
- src/frontend/src/pages/LoginPage.jsx
> Logout Feature, and docker set up for frontend
